### ISSUE TITLE
NetTV.GX-1000.apk

### ISSUE THREAD

**Issue by sadminnp** [Astronxd/NetTV-WorldLink#1]
yo apps install vayena ne

**Comment by Astronxd** [comment]
k error aayo ?

**Comment by sadminnp** [comment]
bro lai nettv ko app share garnu na vako raxa tara i got from google and while opening it show ad tespaxi aru khie aaudina so yesko soln k hola ani emulator ma garnu milxa ki nai tyo pani vane dinu hola

**Comment by Astronxd** [comment]
Maile upload gareko app, box bata extract gareko ho. Google bata download gareko playstore version hola. So google ma bheteko app ko problem google mai search garnu hola.

**Comment by Astronxd** [comment]
Error not explained.
